version: "3" 
#The ver of Docker
services:
#start of the configuration of wordpress and mysql

  db:
    #setting up for the db/mysql
    image: mysql:5.7
    #sets up the image and version of mysql
    restart: always
    #if the container is stoped it restarts
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    #Lines 12-16: sets up root password, database name, and user name


  wordpress:
    #setting up wordpress
    depends_on:
      - db
    #Lines 22-23: will not proceed with anything below untill the db is fully complete

    image: wordpress:latest
    #sets up the image and version of wordpress

    restart: always
    #if the container is stoped it restarts

    ports:
      - "8001:80"
    #gives a port to wordpress to be accsessed

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    #Lines 36-39: tells wordpress the root password, database name, and user name
